<?php
/**
 * Created by PhpStorm.
 * User: kchapple
 * Date: 9/24/18
 * Time: 2:47 PM
 */

namespace CareSet\ZermeloBladeGraph\Models;


use CareSet\Zermelo\Models\DatabaseCache;
use CareSet\Zermelo\Models\ZermeloReport;

class CachedGraphReport extends DatabaseCache
{
    protected $graph_nodes_table = null;
    protected $graph_weights_table = null;

    public function __construct( ZermeloReport $report )
    {
        // Cache the "main" query
        parent::__construct( $report );

        return true;
    }

    public function createTable()
    {
        parent::createTable(); // TODO: Change the autogenerated stub

        // Also need to make the node and weight tables

    }

}